version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - apt-get update -y
      - apt-get install -y docker.io
      - dockerd > /dev/null 2>&1 &
      - sudo docker --version
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | sudo docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - sudo docker push ankush152002/monitoring-app:latest

artifacts:
  files:
    - '**/*'
