options:
  logging: CLOUD_LOGGING_ONLY # No logging bucket

steps:
  # Step 1: Pull the Docker image from Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker.io/an/ankush152002/system-monitoring-app:latest']

  # Step 2: Run SonarQube scan
  - name: 'sonarsource/sonar-scanner-cli'
    env:
      - 'SONAR_TOKEN=${_SONAR_TOKEN}'  # Pass SonarQube token as environment variable
    args:
      - 'sonar-scanner'
      - '-Dsonar.projectKey=cloudbuild123'
      - '-Dsonar.sources=src'
      - '-Dsonar.host.url=http://34.42.227.155:9000'  # Replace with your SonarQube server URL
      - '-Dsonar.login=${_SONAR_TOKEN}'  # Use token for authentication

  

  # Step 4: Push the Docker image back to Docker Hub (if scans pass)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'docker.io/an/ankush152002/system-monitoring-app:latest'

# Substitutions (for the SonarQube token)
substitutions:
  _SONAR_TOKEN: 'sqp_a2de61de7b7df8d04775a320c152068e73a4c05c'

options:
  logging: CLOUD_LOGGING_ONLY  # Disable default logging, adjust as needed
