options:
  logging: CLOUD_LOGGING_ONLY  # Enable Cloud Logging for debugging

steps:
  # Step 1: Authenticate to Docker Hub using substitutions for credentials
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$_DOCKER_PASSWORD" | docker login -u "$_DOCKER_USERNAME" --password-stdin
        docker pull docker.io/ankush152002/system-monitoring-app@sha256:af1f3176995609bdec7d02fa39d82196a03e7c00a79bc03f3511b1c8d3f6ed09

  # Step 3: Sign the image with Binary Authorization (Optional, if required)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'beta'
      - 'container'
      - 'binauthz'
      - 'attestations'
      - 'sign-and-create'
      - '--artifact-url=docker.io/ankush152002/system-monitoring-app@sha256:af1f3176995609bdec7d02fa39d82196a03e7c00a79bc03f3511b1c8d3f6ed09'
      - '--attestor=anilk'  # Replace with your attestor name
      - '--attestor-project=cloudbuild-450108'  # Replace with your project ID
      - '--keyversion=projects/cloudbuild-450108/locations/global/keyRings/binaryauthorization-keys/cryptoKeys/demo-key/cryptoKeyVersions/1'

  # Step 4: Verify image with Binary Authorization before deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'beta'
      - 'container'
      - 'binauthz'
      - 'attestations'
      - 'list'
      - '--artifact-url=docker.io/ankush152002/system-monitoring-app@sha256:af1f3176995609bdec7d02fa39d82196a03e7c00a79bc03f3511b1c8d3f6ed09'

  # Step 5: Deploy to GKE (if verification is successful)
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=deployment.yml'
      - '--image=docker.io/ankush152002/system-monitoring-app@sha256:af1f3176995609bdec7d02fa39d82196a03e7c00a79bc03f3511b1c8d3f6ed09'
      - '--cluster=sonar-cluster'
      - '--location=us-central1-a'

options:
  logging: CLOUD_LOGGING_ONLY  # Enable Cloud Log
