apiVersion: v1
kind: Service
metadata:
  name: system-monitoring-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: system-monitoring

