apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-monitoring-app
  template:
    metadata:
      labels:
        app: system-monitoring-app
    spec:
      containers:
      - name: system-monitoring-app
        image: system-monitoring-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000

