apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-monitoring-app
  template:
    metadata:
      labels:
        app: system-monitoring-app
    spec:
      containers:
      - name: system-monitoring-app
        image: system-monitoring-app:latest  # Specify a specific version tag if possible
        imagePullPolicy: IfNotPresent  # Change this if you want to pull the image if not present locally
        ports:
        - containerPort: 5000
