apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-monitoring-app
  template:
    metadata:
      labels:
        app: system-monitoring-app
    spec:
      containers:
      - name: system-monitoring-app
        image: ankush152002/system-monitoring-app:10825486346  # Specify a specific version tag if possible
        imagePullPolicy: IfNotPresent  # Change this if you want to pull the image if not present locally
        ports:
        - containerPort: 5000
        env:
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_PASSPORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSPORT
        
